// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiLth0F4Yo-VryKfuaiYbCWkWXOy-ScpM',
    appId: '1:333517396912:web:083e32695b4131f3789475',
    messagingSenderId: '333517396912',
    projectId: 'rachnabus',
    authDomain: 'rachnabus.firebaseapp.com',
    storageBucket: 'rachnabus.firebasestorage.app',
    measurementId: 'G-FXRLVR668B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk4kFW1mMD8l5qMS1hWBpN80MbbsPV7OA',
    appId: '1:333517396912:android:2e6b9daa33705dc6789475',
    messagingSenderId: '333517396912',
    projectId: 'rachnabus',
    storageBucket: 'rachnabus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxYlK6KCNVIcCViqqH8NXBaQX4cQmVpxk',
    appId: '1:333517396912:ios:10f1853c84dff4c1789475',
    messagingSenderId: '333517396912',
    projectId: 'rachnabus',
    storageBucket: 'rachnabus.firebasestorage.app',
    iosBundleId: 'com.example.hmmm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxYlK6KCNVIcCViqqH8NXBaQX4cQmVpxk',
    appId: '1:333517396912:ios:10f1853c84dff4c1789475',
    messagingSenderId: '333517396912',
    projectId: 'rachnabus',
    storageBucket: 'rachnabus.firebasestorage.app',
    iosBundleId: 'com.example.hmmm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiLth0F4Yo-VryKfuaiYbCWkWXOy-ScpM',
    appId: '1:333517396912:web:b00bc5a9c29e9a7c789475',
    messagingSenderId: '333517396912',
    projectId: 'rachnabus',
    authDomain: 'rachnabus.firebaseapp.com',
    storageBucket: 'rachnabus.firebasestorage.app',
    measurementId: 'G-DVHXDP9N11',
  );
}
